from pydantic import BaseModel

class URLTarget(BaseModel):
    """Subclass of BaseModel defining schema of JSON. Defines what the 
    API expects in the request body.

    Attributes:
        url (str): The actual URL of the website
        
    """
    url: str

class URLShort(BaseModel):
    """Subclass of BaseModel defining schema of JSON. Defines what the 
    client expects in the response body.

    Attributes:
        url (str): The shortened URL generated by the API
        
    """
    url: str